version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
  "bootstrap/**",
  "database/**",
  "docker-config/**",
  "public/**",
  "resources/**",
  "storage/**",
  "vendor/**",
  "node_modules/**"
]

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "php"
enabled = true
